const ROLES = {
    ADMIN: "Admin",
    HR: "HR", // mapped to Recruiter for backwards compatibility
    RECRUITER: "Recruiter",
    HIRING_MANAGER: "Hiring Manager",
    INTERVIEWER: "Interviewer",
    CANDIDATE: "Candidate"
};

const PERMISSIONS = {
    TEAM_VIEW: "TEAM_VIEW",
    TEAM_INVITE: "TEAM_INVITE",
    TEAM_UPDATE_ROLE: "TEAM_UPDATE_ROLE",
    TEAM_DEACTIVATE: "TEAM_DEACTIVATE",
    TEAM_REMOVE: "TEAM_REMOVE",

    JOB_VIEW: "JOB_VIEW",
    JOB_CREATE: "JOB_CREATE",
    JOB_UPDATE: "JOB_UPDATE",
    JOB_DELETE: "JOB_DELETE",
    JOB_PUBLISH: "JOB_PUBLISH",
    JOB_ASSIGN_TEAM: "JOB_ASSIGN_TEAM",

    CANDIDATE_VIEW: "CANDIDATE_VIEW",
    CANDIDATE_UPDATE: "CANDIDATE_UPDATE",

    APPLICATION_VIEW: "APPLICATION_VIEW",
    APPLICATION_UPDATE: "APPLICATION_UPDATE",
    APPLICATION_MOVE_PIPELINE: "APPLICATION_MOVE_PIPELINE",

    AI_ANALYSIS_VIEW: "AI_ANALYSIS_VIEW",
    AI_ANALYSIS_RUN: "AI_ANALYSIS_RUN",

    INTERVIEW_VIEW: "INTERVIEW_VIEW",
    INTERVIEW_CREATE: "INTERVIEW_CREATE",
    INTERVIEW_UPDATE: "INTERVIEW_UPDATE",
    INTERVIEW_CANCEL: "INTERVIEW_CANCEL",
    INTERVIEW_FEEDBACK_SUBMIT: "INTERVIEW_FEEDBACK_SUBMIT",

    ANALYTICS_VIEW: "ANALYTICS_VIEW",
    REPORT_GENERATE: "REPORT_GENERATE",
    DATA_EXPORT: "DATA_EXPORT",

    COMMUNICATION_VIEW: "COMMUNICATION_VIEW",
    COMMUNICATION_SEND: "COMMUNICATION_SEND",
    TEMPLATE_MANAGE: "TEMPLATE_MANAGE",

    ORGANIZATION_VIEW: "ORGANIZATION_VIEW",
    ORGANIZATION_UPDATE: "ORGANIZATION_UPDATE",

    AUDIT_LOG_VIEW: "AUDIT_LOG_VIEW",
    SYSTEM_INFO_VIEW: "SYSTEM_INFO_VIEW"
};

const ROLE_PERMISSIONS = {
    [ROLES.ADMIN]: Object.values(PERMISSIONS),
    [ROLES.HR]: [
        PERMISSIONS.TEAM_VIEW,
        PERMISSIONS.JOB_VIEW,
        PERMISSIONS.JOB_CREATE,
        PERMISSIONS.JOB_UPDATE,
        PERMISSIONS.JOB_PUBLISH,
        PERMISSIONS.JOB_ASSIGN_TEAM,
        PERMISSIONS.CANDIDATE_VIEW,
        PERMISSIONS.CANDIDATE_UPDATE,
        PERMISSIONS.APPLICATION_VIEW,
        PERMISSIONS.APPLICATION_UPDATE,
        PERMISSIONS.APPLICATION_MOVE_PIPELINE,
        PERMISSIONS.AI_ANALYSIS_VIEW,
        PERMISSIONS.AI_ANALYSIS_RUN,
        PERMISSIONS.INTERVIEW_VIEW,
        PERMISSIONS.INTERVIEW_CREATE,
        PERMISSIONS.INTERVIEW_UPDATE,
        PERMISSIONS.INTERVIEW_CANCEL,
        PERMISSIONS.INTERVIEW_FEEDBACK_SUBMIT,
        PERMISSIONS.ANALYTICS_VIEW,
        PERMISSIONS.REPORT_GENERATE,
        PERMISSIONS.DATA_EXPORT,
        PERMISSIONS.COMMUNICATION_VIEW,
        PERMISSIONS.COMMUNICATION_SEND,
        PERMISSIONS.TEMPLATE_MANAGE,
        PERMISSIONS.ORGANIZATION_VIEW
    ],
    [ROLES.RECRUITER]: [
        PERMISSIONS.TEAM_VIEW,
        PERMISSIONS.JOB_VIEW,
        PERMISSIONS.JOB_CREATE,
        PERMISSIONS.JOB_UPDATE,
        PERMISSIONS.JOB_PUBLISH,
        PERMISSIONS.JOB_ASSIGN_TEAM,
        PERMISSIONS.CANDIDATE_VIEW,
        PERMISSIONS.CANDIDATE_UPDATE,
        PERMISSIONS.APPLICATION_VIEW,
        PERMISSIONS.APPLICATION_UPDATE,
        PERMISSIONS.APPLICATION_MOVE_PIPELINE,
        PERMISSIONS.AI_ANALYSIS_VIEW,
        PERMISSIONS.AI_ANALYSIS_RUN,
        PERMISSIONS.INTERVIEW_VIEW,
        PERMISSIONS.INTERVIEW_CREATE,
        PERMISSIONS.INTERVIEW_UPDATE,
        PERMISSIONS.INTERVIEW_CANCEL,
        PERMISSIONS.INTERVIEW_FEEDBACK_SUBMIT,
        PERMISSIONS.ANALYTICS_VIEW,
        PERMISSIONS.REPORT_GENERATE,
        PERMISSIONS.DATA_EXPORT,
        PERMISSIONS.COMMUNICATION_VIEW,
        PERMISSIONS.COMMUNICATION_SEND,
        PERMISSIONS.TEMPLATE_MANAGE,
        PERMISSIONS.ORGANIZATION_VIEW
    ],
    [ROLES.HIRING_MANAGER]: [
        PERMISSIONS.JOB_VIEW,
        PERMISSIONS.CANDIDATE_VIEW,
        PERMISSIONS.APPLICATION_VIEW,
        PERMISSIONS.AI_ANALYSIS_VIEW,
        PERMISSIONS.INTERVIEW_VIEW,
        PERMISSIONS.INTERVIEW_FEEDBACK_SUBMIT,
        PERMISSIONS.ANALYTICS_VIEW,
        PERMISSIONS.COMMUNICATION_VIEW,
        PERMISSIONS.ORGANIZATION_VIEW
    ],
    [ROLES.INTERVIEWER]: [
        PERMISSIONS.INTERVIEW_VIEW,
        PERMISSIONS.INTERVIEW_FEEDBACK_SUBMIT,
        PERMISSIONS.ORGANIZATION_VIEW
    ],
    [ROLES.CANDIDATE]: [
        PERMISSIONS.JOB_VIEW
    ]
};

const hasPermission = (role, permission) => {
    const permissions = ROLE_PERMISSIONS[role] || [];
    return permissions.includes(permission);
};

module.exports = {
    ROLES,
    PERMISSIONS,
    ROLE_PERMISSIONS,
    hasPermission
};
